---
title: "22-23学年第二学期计划"
author: "王岳森"
output:
  xaringan::moon_reader:
    css: [default, zh-CN.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

class: left, middle

# 上学期课程

- 中级微观经济学

- 高级数理统计专题

- 国民经济核算

---
class: left, middle

# 阅读的文献

- Athey, S. , G. W. Imbens . "Machine Learning Methods for Estimating Heterogeneous Causal Eects." (2015).

- Knaus, M. C. , M. Lechner , A. Strittmatter . "Heterogeneous Employment Effects of Job Search Programmes: A Machine Learning Approach." Journal of Human Resources (2017).

- 胡安宁, 吴晓刚, 陈云松. "处理效应异质性分析——机器学习方法带来的机遇与挑战." 社会学研究 1(2021):25.

- 钱浩祺, 龚嫣然, 吴力波. "更精确的因果效应识别:基于机器学习的视角." 计量经济学报 4(2021):25.

---
class: inverse, center, middle

# 新学期

---
class: left, middle

# 上学期的期末考试

- 中级微观经济学

- 高级数理统计专题

---
class: left, middle

# 本学期的课程

- 中级宏观经济学

- 中级计量经济学

- 多元统计分析

- 应用统计专题讨论

- 统计计算

---
class: left, middle

# Econometric Evaluation of Socio-Economic Programs

## Theory and Applications (Second Edition)

- Chapter 5 Difference-in-Differences with Many Pre- and Post-Treatment Times

- Chapter 6 Synthetic Control Method

---
class: left, middle

# 可能阅读的书：

- Causal Inference in Statistics: A Primer（翻译版）， Judea Pearl等著

- 因果推断与机器学习，郭若城等编著

- Causality: Models, Reasoning and Inference（翻译版）， Judea Pearl著

---
class: middle, center, inverse

# The end